language: php

php:
  - 5.6
  - 7.0
  - hhvm

before_script:
  - composer self-update
  - composer install --prefer-source --dev --no-interaction
  - phpenv rehash

script:
  - "vendor/bin/tester tests/"