language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
    fast_finish: true
    allow_failures:
        - php: 7.0
        - php: hhvm

before_script:
  - composer self-update
  - composer install --prefer-source --dev --no-interaction
  - phpenv rehash

script:
  - "vendor/bin/tester tests/"